import { detectHostDnsServers, DEFAULT_DNS_SERVERS } from './dns-resolver';
import * as fs from 'fs';

jest.mock('fs');
const mockedFs = fs as jest.Mocked<typeof fs>;

const mockLogger = {
  debug: jest.fn(),
  info: jest.fn(),
  warn: jest.fn(),
  error: jest.fn(),
  success: jest.fn(),
  setLevel: jest.fn(),
};

beforeEach(() => {
  jest.clearAllMocks();
});

describe('parseResolvConf (via detectHostDnsServers)', () => {
  it('extracts nameservers from standard content', () => {
    mockedFs.readFileSync.mockReturnValue(`# Generated by systemd-resolved
nameserver 1.1.1.1
nameserver 9.9.9.9
search example.com
`);
    expect(detectHostDnsServers(mockLogger as any)).toEqual(['1.1.1.1', '9.9.9.9']);
  });

  it('ignores comments and empty lines', () => {
    mockedFs.readFileSync.mockReturnValue(`
# This is a comment
; Another comment style

nameserver 1.1.1.1

# nameserver 2.2.2.2
nameserver 8.8.8.8
`);
    expect(detectHostDnsServers(mockLogger as any)).toEqual(['1.1.1.1', '8.8.8.8']);
  });

  it('skips invalid IPs', () => {
    mockedFs.readFileSync.mockReturnValue(`nameserver 1.1.1.1
nameserver not-an-ip
nameserver 8.8.8.8
`);
    expect(detectHostDnsServers(mockLogger as any)).toEqual(['1.1.1.1', '8.8.8.8']);
  });

  it('handles IPv6 nameservers (loopback filtered by detectHostDnsServers)', () => {
    mockedFs.readFileSync.mockReturnValue(`nameserver 2001:4860:4860::8888
nameserver 1.1.1.1
nameserver ::1
`);
    // ::1 is loopback so detectHostDnsServers filters it out
    expect(detectHostDnsServers(mockLogger as any)).toEqual(['2001:4860:4860::8888', '1.1.1.1']);
  });
});

describe('detectHostDnsServers', () => {
  it('filters out 127.0.0.11 (Docker embedded DNS)', () => {
    mockedFs.readFileSync.mockReturnValue(
      'nameserver 127.0.0.11\nnameserver 1.1.1.1\nnameserver 8.8.8.8\n'
    );
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(['1.1.1.1', '8.8.8.8']);
  });

  it('filters out 127.0.0.53 and tries secondary file', () => {
    mockedFs.readFileSync.mockImplementation((filePath: any) => {
      if (filePath === '/run/systemd/resolve/resolv.conf') {
        throw new Error('ENOENT');
      }
      if (filePath === '/etc/resolv.conf') {
        return 'nameserver 127.0.0.53\n';
      }
      throw new Error('ENOENT');
    });
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(DEFAULT_DNS_SERVERS);
    expect(mockLogger.warn).toHaveBeenCalled();
  });

  it('returns DEFAULT_DNS_SERVERS when no files are readable', () => {
    mockedFs.readFileSync.mockImplementation(() => {
      throw new Error('ENOENT');
    });
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(DEFAULT_DNS_SERVERS);
    expect(mockLogger.warn).toHaveBeenCalledWith(
      expect.stringContaining('falling back to')
    );
  });

  it('uses first readable file with usable servers', () => {
    mockedFs.readFileSync.mockImplementation((filePath: any) => {
      if (filePath === '/run/systemd/resolve/resolv.conf') {
        return 'nameserver 9.9.9.9\nnameserver 1.1.1.1\n';
      }
      return 'nameserver 8.8.8.8\n';
    });
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(['9.9.9.9', '1.1.1.1']);
    expect(mockLogger.info).toHaveBeenCalledWith(
      expect.stringContaining('/run/systemd/resolve/resolv.conf')
    );
  });

  it('filters out ::1 IPv6 loopback', () => {
    mockedFs.readFileSync.mockReturnValue(
      'nameserver ::1\nnameserver 2001:4860:4860::8888\n'
    );
    const result = detectHostDnsServers(mockLogger as any);
    expect(result).toEqual(['2001:4860:4860::8888']);
  });
});

describe('DEFAULT_DNS_SERVERS', () => {
  it('should have correct default DNS servers', () => {
    expect(DEFAULT_DNS_SERVERS).toEqual(['8.8.8.8', '8.8.4.4']);
  });
});
